name: Go CD

on:
  push:
    branches:
      - test-cd-pipeline

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get short Git commit SHA
      run: |
        echo "::set-env name=GIT_SHA::$(git rev-parse --short HEAD)"

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.REGISTRY_IMAGE }}:${{ env.GIT_SHA }}
          ${{ secrets.REGISTRY_IMAGE }}:latest
